name:  Documentation
description: Mejoras o correcciones en la documentaci贸n
title: "[DOCS] "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Ay煤danos a mejorar la documentaci贸n de NinjaScript.
  
  - type: dropdown
    id: doc-type
    attributes:
      label: Tipo de mejora
      description: 驴Qu茅 tipo de mejora en documentaci贸n?
      options:
        - Correcci贸n de error/typo
        - Informaci贸n faltante
        - Ejemplo de c贸digo
        - Explicaci贸n m谩s clara
        - Nueva secci贸n
        - Traducci贸n
    validations:
      required: true
      
  - type: input
    id: doc-section
    attributes:
      label: Secci贸n afectada
      description: 驴Qu茅 secci贸n de la documentaci贸n?
      placeholder: "ej. docs/01-fundamentos/onbarupdate.md"
    validations:
      required: true
      
  - type: textarea
    id: improvement
    attributes:
      label: Mejora sugerida
      description: Describe la mejora o correcci贸n necesaria
      placeholder: La documentaci贸n deber铆a incluir...
    validations:
      required: true